
/* =========================================================
   1. PAIS
   ========================================================= */

CREATE TABLE PAIS (
    id_pais NUMBER(3)
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 9 INCREMENT BY 3),
    nom_pais VARCHAR2(30),

    CONSTRAINT PAIS_PK PRIMARY KEY (id_pais)
);


/* =========================================================
   2. CIUDAD
   ========================================================= */

CREATE TABLE CIUDAD (
    id_ciudad NUMBER(3),
    nom_ciudad VARCHAR2(30),
    cod_pais NUMBER(3),

    CONSTRAINT CIUDAD_PK PRIMARY KEY (id_ciudad),

    CONSTRAINT CIUDAD_FK_PAIS
        FOREIGN KEY (cod_pais)
        REFERENCES PAIS(id_pais)
);


/* =========================================================
   3. SUCURSAL
   ========================================================= */

CREATE TABLE SUCURSAL (
    id_sucursal CHAR(3),
    nom_sucursal VARCHAR2(20),
    calle VARCHAR2(20),
    num_calle NUMBER(4),
    cod_ciudad NUMBER(3),

    CONSTRAINT SUCURSAL_PK PRIMARY KEY (id_sucursal),

    CONSTRAINT SUCURSAL_FK_CIUDAD
        FOREIGN KEY (cod_ciudad)
        REFERENCES CIUDAD(id_ciudad)
);


/* =========================================================
   4. SERVICIO
   ========================================================= */

CREATE TABLE SERVICIO (
    id_servicio NUMBER(3),
    descripcion VARCHAR2(100),
    costo NUMBER(7),

    CONSTRAINT SERVICIO_PK PRIMARY KEY (id_servicio)
);


/* =========================================================
   5. MARCA
   ========================================================= */

CREATE TABLE MARCA (
    id_marca NUMBER(2),
    descripcion VARCHAR2(20),

    CONSTRAINT MARCA_PK PRIMARY KEY (id_marca)
);


/* =========================================================
   6. MODELO
   ========================================================= */

CREATE TABLE MODELO (
    id_modelo NUMBER(5),
    marca_id NUMBER(2),
    descripcion VARCHAR2(20),

    CONSTRAINT MODELO_PK
        PRIMARY KEY (id_modelo, marca_id),

    CONSTRAINT MODELO_FK_MARCA
        FOREIGN KEY (marca_id)
        REFERENCES MARCA(id_marca)
);


/* =========================================================
   7. TIPO_AUTOMOVIL
   ========================================================= */

CREATE TABLE TIPO_AUTOMOVIL (
    id_tipo CHAR(3),
    descripcion VARCHAR2(20),

    CONSTRAINT TIPO_AUTOMOVIL_PK
        PRIMARY KEY (id_tipo)
);


/* =========================================================
   8. CLIENTE
   ========================================================= */

CREATE TABLE CLIENTE (
    rut NUMBER(8),
    dv CHAR(1),
    pnombre VARCHAR2(20),
    snombre VARCHAR2(20),
    apaterno VARCHAR2(20),
    amaterno VARCHAR2(20),
    telefono VARCHAR2(12),
    email VARCHAR2(40),
    tipo_cli CHAR(1),

    CONSTRAINT CLIENTE_PK PRIMARY KEY (rut)
);


/* =========================================================
   9. MECANICO
   ========================================================= */

CREATE TABLE MECANICO (
    cod_mecanico NUMBER(5)
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 460 INCREMENT BY 7),
    pnombre VARCHAR2(20),
    snombre VARCHAR2(20),
    apaterno VARCHAR2(20),
    amaterno VARCHAR2(20),
    bono_jefatura NUMBER(10),
    sueldo NUMBER(10),
    monto_impuestos NUMBER(10),
    cod_supervisor NUMBER(5),

    CONSTRAINT MECANICO_PK
        PRIMARY KEY (cod_mecanico),

    CONSTRAINT MECANICO_FK_MECANICO
        FOREIGN KEY (cod_supervisor)
        REFERENCES MECANICO(cod_mecanico)
);


/* =========================================================
   10. AUTOMOVIL
   ========================================================= */

CREATE TABLE AUTOMOVIL (
    patente CHAR(8),
    annio NUMBER(4),
    cant_puertas NUMBER(1),
    km NUMBER(6),
    color VARCHAR2(30),
    cod_tipo_auto CHAR(3),
    cod_modelo NUMBER(5),
    cod_marca NUMBER(2),
    cl_rut NUMBER(8),

    CONSTRAINT AUTOMOVIL_PK
        PRIMARY KEY (patente),

    CONSTRAINT AUTOMOVIL_FK_CLIENTE
        FOREIGN KEY (cl_rut)
        REFERENCES CLIENTE(rut),

    CONSTRAINT AUTOMOVIL_FK_MODELO
        FOREIGN KEY (cod_modelo, cod_marca)
        REFERENCES MODELO(id_modelo, marca_id),

    CONSTRAINT AUTOMOVIL_FK_TIPO
        FOREIGN KEY (cod_tipo_auto)
        REFERENCES TIPO_AUTOMOVIL(id_tipo)
);


/* =========================================================
   11. MANTENCION
   ========================================================= */

CREATE TABLE MANTENCION (
    num_mantencion NUMBER(4),
    cod_sucursal CHAR(3),
    fecha_ingreso DATE,
    fecha_salida DATE,
    patente_auto CHAR(8),
    cod_mecanico NUMBER(5),
    costo_total NUMBER(7),
    estado VARCHAR2(15),

    CONSTRAINT MANTENCION_PK
        PRIMARY KEY (num_mantencion),

    CONSTRAINT MANT_FK_AUTOMOVIL
        FOREIGN KEY (patente_auto)
        REFERENCES AUTOMOVIL(patente),

    CONSTRAINT MANT_FK_MECANICO
        FOREIGN KEY (cod_mecanico)
        REFERENCES MECANICO(cod_mecanico),

    CONSTRAINT MANT_FK_SUCURSAL
        FOREIGN KEY (cod_sucursal)
        REFERENCES SUCURSAL(id_sucursal)
);


/* =========================================================
   12. DETALLE_SERVICIO
   ========================================================= */

CREATE TABLE DETALLE_SERVICIO (
    mantencion_num NUMBER(4),
    cod_servicio NUMBER(3),
    descuento_serv NUMBER(4,3),
    cantidad NUMBER(3),

    CONSTRAINT DETALLE_SERVICIO_PK
        PRIMARY KEY (mantencion_num, cod_servicio),

    CONSTRAINT DET_SERV_FK_MANTENCION
        FOREIGN KEY (mantencion_num)
        REFERENCES MANTENCION(num_mantencion),

    CONSTRAINT DET_SERV_FK_SERVICIO
        FOREIGN KEY (cod_servicio)
        REFERENCES SERVICIO(id_servicio)
);


/* =========================================================
   13. ESTANDAR
   ========================================================= */

CREATE TABLE ESTANDAR (
    cl_rut NUMBER(8),
    puntaje_fidelidad NUMBER(10),

    CONSTRAINT NORMAL_PK
        PRIMARY KEY (cl_rut),

    CONSTRAINT NORMAL_FK_CLIENTE
        FOREIGN KEY (cl_rut)
        REFERENCES CLIENTE(rut)
);


/* =========================================================
   14. PREMIUM
   ========================================================= */

CREATE TABLE PREMIUM (
    cl_rut NUMBER(8),
    pesos_clientes NUMBER(10),
    monto_credito NUMBER(10),

    CONSTRAINT PREMIUM_PK
        PRIMARY KEY (cl_rut),

    CONSTRAINT PREMIUM_FK_CLIENTE
        FOREIGN KEY (cl_rut)
        REFERENCES CLIENTE(rut)
);


-- ============================================
-- CASO 2: MODIFICACIÓN DEL MODELO
-- ============================================

-- 1. Eliminar atributo derivado
ALTER TABLE MANTENCION
DROP COLUMN COSTO_TOTAL;


-- 2. Agregar sucursal a DETALLE_SERVICIO
ALTER TABLE DETALLE_SERVICIO
ADD COD_SUCURSAL CHAR(3);


-- 3. Eliminar FK antigua
ALTER TABLE DETALLE_SERVICIO
DROP CONSTRAINT DET_SERV_FK_MANTENCION;


-- 4. Eliminar PK antigua
ALTER TABLE MANTENCION
DROP CONSTRAINT MANTENCION_PK;


-- 5. Crear nueva PK compuesta
ALTER TABLE MANTENCION
ADD CONSTRAINT MANTENCION_PK
PRIMARY KEY (NUM_MANTENCION, COD_SUCURSAL);


-- 6. Crear nueva FK compuesta
ALTER TABLE DETALLE_SERVICIO
ADD CONSTRAINT DET_SERV_FK_MANTENCION
FOREIGN KEY (MANTENCION_NUM, COD_SUCURSAL)
REFERENCES MANTENCION (NUM_MANTENCION, COD_SUCURSAL);


-- 7. EMAIL único
ALTER TABLE CLIENTE
ADD CONSTRAINT CLIENTE_UN_EMAIL
UNIQUE (EMAIL);


-- 8. DV válido
ALTER TABLE CLIENTE
ADD CONSTRAINT CLIENTE_CK_DV
CHECK (DV IN ('0','1','2','3','4','5','6','7','8','9','K'));


-- 9. Sueldo mínimo
ALTER TABLE MECANICO
ADD CONSTRAINT MECANICO_CK_SUELDO
CHECK (SUELDO >= 510000);


-- 10. Estados permitidos
ALTER TABLE MANTENCION
ADD CONSTRAINT MANTENCION_CK_ESTADO
CHECK (ESTADO IN ('Reserva','Ingresado','Entregado','Anulado'));


INSERT INTO PAIS (nom_pais)
VALUES ('Chile');

INSERT INTO PAIS (nom_pais)
VALUES ('Peru');

INSERT INTO PAIS (nom_pais)
VALUES ('Colombia');

COMMIT;

SELECT * FROM PAIS;


INSERT INTO CIUDAD (id_ciudad, nom_ciudad, cod_pais)
VALUES (165, 'Santiago', 9);

INSERT INTO CIUDAD (id_ciudad, nom_ciudad, cod_pais)
VALUES (170, 'Lima', 12);

INSERT INTO CIUDAD (id_ciudad, nom_ciudad, cod_pais)
VALUES (175, 'Bogotá', 15);

COMMIT;


SELECT * FROM CIUDAD;


INSERT INTO SUCURSAL (id_sucursal, nom_sucursal, calle, num_calle, cod_ciudad)
VALUES ('S01', 'Providencia', 'Av. A. Varas', 234, 165);

INSERT INTO SUCURSAL (id_sucursal, nom_sucursal, calle, num_calle, cod_ciudad)
VALUES ('S02', 'Las 4 esquinas', 'Av. Latina', 669, 170);

INSERT INTO SUCURSAL (id_sucursal, nom_sucursal, calle, num_calle, cod_ciudad)
VALUES ('S03', 'El Cafetero', 'Av. El Faro', 900, 175);

COMMIT;


SELECT * FROM SUCURSAL;


INSERT INTO SERVICIO (id_servicio, descripcion, costo)
VALUES (400, 'Cambio Luces', 45000);

INSERT INTO SERVICIO (id_servicio, descripcion, costo)
VALUES (402, 'Desabolladura', 67000);

INSERT INTO SERVICIO (id_servicio, descripcion, costo)
VALUES (404, 'Revisión Frenos', 30000);

INSERT INTO SERVICIO (id_servicio, descripcion, costo)
VALUES (406, 'Cambio Puerta Trasera', 50000);

COMMIT;


SELECT * FROM SERVICIO;


INSERT INTO MECANICO VALUES
(DEFAULT, 'Jorge', 'Pablo', 'Soto', 'Sierpe', 540000, 2759000, 223580, NULL);

INSERT INTO MECANICO VALUES
(DEFAULT, 'Pedro', 'Jose', 'Manriquez', 'Corral', NULL, 759000, 23980, NULL);

INSERT INTO MECANICO VALUES
(DEFAULT, 'Sandra', 'Josefa', 'Letelier', 'S.', 0, 659000, 22358, 460);

INSERT INTO MECANICO VALUES
(DEFAULT, 'Felipe', 'M.', 'Vidal', 'A.', NULL, 759000, 23580, 460);

INSERT INTO MECANICO VALUES
(DEFAULT, 'Jose', 'Miguel', 'Troncoso', 'B.', NULL, 659000, 44580, 474);

INSERT INTO MECANICO VALUES
(DEFAULT, 'Juan', 'Pablo', 'Sánchez', 'R.', NULL, 859000, 23380, 474);

INSERT INTO MECANICO VALUES
(DEFAULT, 'Carlos', 'Felipe', 'Soto', 'J.', 0, 597000, 23580, 474);

INSERT INTO MECANICO VALUES
(DEFAULT, 'Alberto', 'P.', 'Cerda', 'Ramirez', NULL, 559000, 22380, 460);

INSERT INTO MECANICO VALUES
(DEFAULT, 'Alejandra', 'Gabriela', 'Infanti', 'R.', NULL, 659000, 22380, 460);

INSERT INTO MECANICO VALUES
(DEFAULT, 'Roberto', 'Patricio', 'Gutierrez', 'Sosa', NULL, 859000, 22380, 460);

COMMIT;

SELECT * FROM MECANICO;


INSERT INTO MANTENCION
(NUM_MANTENCION, COD_SUCURSAL, FECHA_INGRESO, FECHA_SALIDA, PATENTE_AUTO, COD_MECANICO, ESTADO)
VALUES
(101, 'S01', TO_DATE('12-04-2023','DD-MM-YYYY'), NULL, NULL, 481, 'Reserva');

INSERT INTO MANTENCION
(NUM_MANTENCION, COD_SUCURSAL, FECHA_INGRESO, FECHA_SALIDA, PATENTE_AUTO, COD_MECANICO, ESTADO)
VALUES
(102, 'S02', TO_DATE('21-02-2023','DD-MM-YYYY'), TO_DATE('21-02-2023','DD-MM-YYYY'), NULL, 502, 'Entregado');

INSERT INTO MANTENCION
(NUM_MANTENCION, COD_SUCURSAL, FECHA_INGRESO, FECHA_SALIDA, PATENTE_AUTO, COD_MECANICO, ESTADO)
VALUES
(103, 'S02', TO_DATE('09-10-2023','DD-MM-YYYY'), NULL, NULL, 502, 'Anulado');

INSERT INTO MANTENCION
(NUM_MANTENCION, COD_SUCURSAL, FECHA_INGRESO, FECHA_SALIDA, PATENTE_AUTO, COD_MECANICO, ESTADO)
VALUES
(104, 'S03', TO_DATE('11-08-2023','DD-MM-YYYY'), TO_DATE('18-08-2023','DD-MM-YYYY'), NULL, 509, 'Entregado');

INSERT INTO MANTENCION
(NUM_MANTENCION, COD_SUCURSAL, FECHA_INGRESO, FECHA_SALIDA, PATENTE_AUTO, COD_MECANICO, ESTADO)
VALUES
(105, 'S03', TO_DATE('03-12-2023','DD-MM-YYYY'), NULL, NULL, 509, 'Ingresado');

COMMIT;

SELECT * FROM MANTENCION;


-- ============================================
-- INFORME 1
-- Listado de mecánicos con reajuste de sueldo
-- ============================================

SELECT
    COD_MECANICO AS "IDENTIFICADOR",
    PNOMBRE || ' ' || SNOMBRE || ' ' || APATERNO || ' ' || AMATERNO AS "MECANICO",
    SUELDO AS "SALARIO ACTUAL",
    SUELDO * 0.05 AS "AJUSTE",
    SUELDO * 1.05 AS "SUELDO REAJUSTADO"
FROM MECANICO
WHERE SUELDO BETWEEN 600000 AND 900000
   OR COD_SUPERVISOR IS NULL
ORDER BY SUELDO ASC,
         "MECANICO" DESC;
         
         
   -- ============================================
-- INFORME 2
-- Listado de cálculo de reajustes de sueldos
-- ============================================

SELECT
    COD_MECANICO AS "IDENTIFICADOR",
    PNOMBRE || ' ' || SNOMBRE || ' ' || APATERNO || ' ' || AMATERNO AS "MECANICO",
    SUELDO AS "SALARIO ACTUAL",
    SUELDO * 0.05 AS "AJUSTE",
    SUELDO * 1.05 AS "SUELDO REAJUSTADO"
FROM MECANICO
WHERE SUELDO BETWEEN 600000 AND 900000
   OR COD_SUPERVISOR IS NULL
ORDER BY SUELDO ASC,
         "MECANICO" DESC;      

